---

- name: Configure timezone
  include_tasks: timezone.yml
  tags:
    - role::chrony
    - role::chrony::configure
    - role::chrony::timezone

- name: Configure chrony daemon
  include_tasks: chrony.yml
  tags:
    - role::chrony
    - role::chrony::configure
